### PR TITLE
Depend on traceviewer directly

### PR DESCRIPTION
**Pull request by dstockwell**

### CODE REVIEW

**Comment by dstockwell** [comment]
@shans this seems to be failing in the memory dump phases. There's a timeout on travis, but `gulp travis-test` passes for me locally.

**Comment by shans** [comment]
Happy to merge, but we probably need to get the tests happy somehow.

**Comment by dstockwell** [comment]
No rush. Should try to resolve the failure first, but I'm not sure what it is.

**Comment by dstockwell** [comment]
I think it just takes a long time to load traceviewer. E.g. on Pixel2:

    > var start = Date.now(); var tv = require('traceviewer'); Date.now() - start
    837

**Comment by dstockwell** [comment]
Found a workaround, I'll file a bug on traceviewer.

**Pull request merged**
